title: Ola Sanusi, PhD # your name (or website title) here
logo: "/images/ola.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <b>Educator | Data Scientist | Researcher</b>
   
  If you would like to learn more about me, feel free to have a look at my resume.

  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
